name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Package
        uses: ConorMacBride/install-package@v1.1.0
        with:
          brew: llvm@11 python@3.11
        
      - name: Alias
        run: alias python="python3"

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0
          
      - name: conf-python
        run: |
          opam install conf-python-3.1.0.0 menhir
          eval $(opam env)

      - name: Installing deps
        run: opam install . --deps-only --with-doc
        shell: bash
      
      - name: Run tests 
        run: |
          rm *.opam
          opam exec -- dune build
          opam exec -- dune runtest
